# config/services.yaml
parameters:
    # Définir vos paramètres ici si nécessaire

services:
    # Configuration par défaut pour tous les services
    _defaults:
        autowire: true      # Active l’autowiring pour tous les services
        autoconfigure: true # Active l’autoconfiguration pour tous les services

    # Configuration explicite pour CartManager
    App\Service\CartManager:
        arguments:
            $requestStack: '@request_stack'  # Injecte le service "request_stack"

    # Configuration pour inclure tous les services dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'